apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: z9z7ok2qm-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: z9z7ok2qm-python 
  name: z9z7ok2qm-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: z9z7ok2qm-python
    weight: 100 
